from typing import Any, Iterable, Sequence

class DeltaGenerator:
    def __enter__(self) -> DeltaGenerator: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...


def set_page_config(*, page_title: str | None = ..., page_icon: str | None = ..., layout: str | None = ...) -> None: ...
def markdown(body: str, unsafe_allow_html: bool = ...) -> None: ...
def text_input(label: str, value: str = ..., **kwargs: Any) -> str: ...
def file_uploader(label: str, type: Sequence[str] | None = ..., **kwargs: Any) -> Any: ...
def columns(spec: Sequence[float] | int, gap: str = ...) -> list[DeltaGenerator]: ...
def subheader(body: str) -> None: ...
def image(image: Any, use_container_width: bool = ...) -> None: ...
def error(body: str) -> None: ...
def stop() -> None: ...
def metric(label: str, value: str) -> None: ...
def info(body: str) -> None: ...
def caption(body: str) -> None: ...
